// Code generated by swaggo/swag. DO NOT EDIT.

package mall_admin

import "github.com/swaggo/swag"

const docTemplatemall_admin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/authTest": {
            "get": {
                "description": "用户鉴权测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "用户鉴权测试",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "删除指定用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "删除指定用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/info": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据用户 ID 获取用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "根据用户 ID 获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/list": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "分页查询用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "分页查询用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pageNum",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户登录",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsAdminLoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/refreshToken": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "刷新 token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "刷新 token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "用户注册",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsAdminRegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/role/update": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改指定用户角色",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "修改指定用户角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "adminId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "角色 ID",
                        "name": "roleIds",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/role/{adminId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取指定用户的角色",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "获取指定用户的角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "adminId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改指定用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "修改指定用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改指定用户信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsAdminUpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/updatePassword": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改指定用户密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "修改指定用户密码",
                "parameters": [
                    {
                        "description": "修改指定用户密码",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsAdminUpdatePasswordDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/updateStatus/{user_id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改指定用户状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "修改指定用户状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/admin/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取指定用户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台用户管理"
                ],
                "summary": "获取指定用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/memberLevel/list": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "查看所有会员等级",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会员等级管理"
                ],
                "summary": "查看所有会员等级",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "是否为默认等级：0-\u003e不是；1-\u003e是",
                        "name": "defaultStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加后台菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "添加后台菜单",
                "parameters": [
                    {
                        "description": "添加后台菜单",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsMenuCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "删除后台菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "删除后台菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/list/{parentId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "分页查询后台菜单",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "分页查询后台菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父级菜单ID",
                        "name": "parentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/treeList": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "树形结构返回所有菜单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "树形结构返回所有菜单列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改后台菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "修改后台菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改后台菜单",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsMenuCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/updateHidden/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改菜单显示状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "修改菜单显示状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "是否隐藏",
                        "name": "hidden",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/menu/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据ID获取菜单详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台菜单管理"
                ],
                "summary": "根据ID获取菜单详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜单ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/attrInfo/{productCategoryId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据分类查询属性列表或参数列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "根据分类查询属性列表或参数列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "productCategoryId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/admin_dto.PmsProductAttributeInfoDTO"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加商品属性分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "添加商品属性分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "属性分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "删除商品属性分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "删除商品属性分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "属性分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/list": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "分页获取所有商品属性分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "分页获取所有商品属性分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pageNum",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/list/withAttr": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取所有商品属性分类及其下属性",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "获取所有商品属性分类及其下属性",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改商品属性分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "修改商品属性分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "属性分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/category/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取单个商品属性分类信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性分类"
                ],
                "summary": "获取单个商品属性分类信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "属性分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加商品属性信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "添加商品属性信息",
                "parameters": [
                    {
                        "description": "修改指定商品属性",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.PmsProductAttributeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/delete": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "批量删除商品属性",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "批量删除商品属性",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "商品属性id集合",
                        "name": "ids",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/list/{cid}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据分类查询属性列表或参数列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "根据分类查询属性列表或参数列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "0表示属性，1表示参数",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改商品属性信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "修改商品属性信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品属性id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改指定商品属性",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.PmsProductAttributeDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productAttribute/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "查询单个商品属性",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品属性管理"
                ],
                "summary": "查询单个商品属性",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品属性id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加商品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "添加商品分类",
                "parameters": [
                    {
                        "description": "添加商品分类",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.PmsProductCategoryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据id删除商品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "根据id删除商品分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/list/withChildren": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "查询所有一级分类及子分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "查询所有一级分类及子分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/list/{parentId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "分页查询商品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "分页查询商品分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父分类的编号",
                        "name": "parentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/update/navStatus": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "批量修改导航状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "批量修改导航状态",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "商品分类id集合",
                        "name": "ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "导航状态",
                        "name": "navStatus",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/update/showStatus": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "批量修改导航状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "批量修改导航状态",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "商品分类id集合",
                        "name": "ids",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "显示状态",
                        "name": "showStatus",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改商品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "修改商品分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改商品分类",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.PmsProductCategoryDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/productCategory/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据id获取商品分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "商品分类"
                ],
                "summary": "根据id获取商品分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "商品分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加后台资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "添加后台资源",
                "parameters": [
                    {
                        "description": "添加后台资源",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsResourceCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据ID删除后台资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "根据ID删除后台资源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "资源id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/list": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "分页模糊查询后台资源",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "分页模糊查询后台资源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "资源分类ID",
                        "name": "categoryId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "资源名称",
                        "name": "nameKeyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "资源URL",
                        "name": "urlKeyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/listAll": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "查询所有后台资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "查询所有后台资源",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改后台资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "修改后台资源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "资源id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改后台资源",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsResourceCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resource/{id}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据ID获取资源详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源管理"
                ],
                "summary": "根据ID获取资源详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "资源id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resourceCategory/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加后台资源分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源分类管理"
                ],
                "summary": "添加后台资源分类",
                "parameters": [
                    {
                        "description": "添加后台资源分类",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsResourceCategoryCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resourceCategory/delete/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "删除后台资源分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源分类管理"
                ],
                "summary": "删除后台资源分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resourceCategory/listAll": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "查询所有后台资源分类",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源分类管理"
                ],
                "summary": "查询所有后台资源分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/resourceCategory/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改后台资源分类",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台资源分类管理"
                ],
                "summary": "修改后台资源分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改后台资源分类",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsResourceCategoryCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/allocMenu/{roleId}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改角色菜单",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "修改角色菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "roleId",
                        "name": "roleId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "menuIds",
                        "name": "menuIds",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/allocResource/{roleId}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "给角色分配资源",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "给角色分配资源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "roleId",
                        "name": "roleId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "resourceIds",
                        "name": "resourceIds",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/create": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "添加角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "添加角色",
                "parameters": [
                    {
                        "description": "添加角色",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsRoleCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/delete": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "批量删除角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "批量删除角色",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "ids",
                        "name": "ids",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/list": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "根据角色名称分页获取角色列表",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "根据角色名称分页获取角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "keyword",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "pageNum",
                        "name": "pageNum",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/listAll": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取所有角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "获取所有角色",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/listMenu/{roleId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取角色相关菜单",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "获取角色相关菜单",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "roleId",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/listResource/{roleId}": {
            "get": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "获取角色相关资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "获取角色相关资源",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "roleId",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/update/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "修改角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改角色",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/admin_dto.UmsRoleCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        },
        "/role/updateStatus/{id}": {
            "post": {
                "security": [
                    {
                        "GinJWTMiddleware": []
                    }
                ],
                "description": "修改角色状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "后台角色管理"
                ],
                "summary": "修改角色状态",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "status",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin_common.GinCommonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "admin_dto.PmsProductAttributeDTO": {
            "type": "object",
            "properties": {
                "filterType": {
                    "description": "分类筛选样式：1-\u003e普通；1-\u003e颜色",
                    "type": "integer"
                },
                "handAddStatus": {
                    "description": "是否支持手动新增；0-\u003e不支持；1-\u003e支持",
                    "type": "integer"
                },
                "inputList": {
                    "description": "可选值列表，以逗号隔开",
                    "type": "string"
                },
                "inputType": {
                    "description": "属性录入方式：0-\u003e手工录入；1-\u003e从列表中选取",
                    "type": "integer"
                },
                "name": {
                    "description": "属性名称",
                    "type": "string"
                },
                "productAttributeCategoryId": {
                    "description": "属性分类ID",
                    "type": "integer"
                },
                "relatedStatus": {
                    "description": "相同属性产品是否关联；0-\u003e不关联；1-\u003e关联",
                    "type": "integer"
                },
                "searchType": {
                    "description": "检索类型；0-\u003e不需要进行检索；1-\u003e关键字检索；2-\u003e范围检索",
                    "type": "integer"
                },
                "selectType": {
                    "description": "属性选择类型：0-\u003e唯一；1-\u003e单选；2-\u003e多选",
                    "type": "integer"
                },
                "sort": {
                    "description": "排序字段",
                    "type": "integer"
                },
                "type": {
                    "description": "属性的类型；0-\u003e规格；1-\u003e参数",
                    "type": "integer"
                }
            }
        },
        "admin_dto.PmsProductAttributeInfoDTO": {
            "type": "object",
            "required": [
                "categoryId"
            ],
            "properties": {
                "categoryId": {
                    "description": "属性ID",
                    "type": "integer"
                }
            }
        },
        "admin_dto.PmsProductCategoryDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "icon": {
                    "description": "图标",
                    "type": "string"
                },
                "keywords": {
                    "description": "关键字",
                    "type": "string"
                },
                "name": {
                    "description": "分类名称",
                    "type": "string"
                },
                "navStatus": {
                    "description": "是否显示在导航栏：0-\u003e不显示；1-\u003e显示",
                    "type": "integer"
                },
                "parentId": {
                    "description": "父分类的编号",
                    "type": "integer"
                },
                "productAttributeIdList": {
                    "description": "产品相关筛选属性集合",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "productUnit": {
                    "description": "分类单位",
                    "type": "string"
                },
                "showStatus": {
                    "description": "显示状态：0-\u003e不显示；1-\u003e显示",
                    "type": "integer"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                }
            }
        },
        "admin_dto.UmsAdminLoginDTO": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密文密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsAdminRegisterDTO": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "icon": {
                    "description": "用户头像",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "note": {
                    "description": "备注",
                    "type": "string"
                },
                "password": {
                    "description": "密文密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsAdminUpdateDTO": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "icon": {
                    "description": "用户头像",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "note": {
                    "description": "备注",
                    "type": "string"
                },
                "password": {
                    "description": "密文密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsAdminUpdatePasswordDTO": {
            "type": "object",
            "required": [
                "newPassword",
                "oldPassword",
                "username"
            ],
            "properties": {
                "newPassword": {
                    "description": "新密码",
                    "type": "string"
                },
                "oldPassword": {
                    "description": "旧密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsMenuCreateDTO": {
            "type": "object",
            "properties": {
                "hidden": {
                    "description": "前端隐藏",
                    "type": "integer"
                },
                "icon": {
                    "description": "前端图标",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "description": "菜单级数",
                    "type": "integer"
                },
                "name": {
                    "description": "前端名称",
                    "type": "string"
                },
                "parentId": {
                    "description": "父级ID",
                    "type": "integer"
                },
                "sort": {
                    "description": "菜单排序",
                    "type": "integer"
                },
                "title": {
                    "description": "菜单名称",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsResourceCategoryCreateDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "资源分类名称",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                }
            }
        },
        "admin_dto.UmsResourceCreateDTO": {
            "type": "object",
            "properties": {
                "categoryId": {
                    "description": "资源分类ID",
                    "type": "integer"
                },
                "description": {
                    "description": "描述",
                    "type": "string"
                },
                "name": {
                    "description": "资源名称",
                    "type": "string"
                },
                "url": {
                    "description": "资源URL",
                    "type": "string"
                }
            }
        },
        "admin_dto.UmsRoleCreateDTO": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "adminCount": {
                    "description": "后台用户数量",
                    "type": "integer"
                },
                "description": {
                    "description": "角色描述",
                    "type": "string"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "sort": {
                    "description": "排序",
                    "type": "integer"
                },
                "status": {
                    "description": "启用状态：0-\u003e禁用；1-\u003e启用",
                    "type": "integer"
                }
            }
        },
        "gin_common.GinCommonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "http 状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回的数据是任意类型\t如果有错误，则把错误信息也封装在此\n\n\t\t{\n\t\t\t\"err_code\": 300000,\n\t\t\t\"err_msg\": \"用户名已存在\"\n\t\t}"
                },
                "message": {
                    "description": "返回的信息 例如: 操作成功或者操作失败",
                    "type": "string"
                },
                "status": {
                    "description": "success or fail",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "GinJWTMiddleware": {
            "description": "Description for what is this security definition being used",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfomall_admin holds exported Swagger Info so clients can modify it
var SwaggerInfomall_admin = &swag.Spec{
	Version:          "v1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "mall-go API",
	Description:      "mall-go API",
	InfoInstanceName: "mall_admin",
	SwaggerTemplate:  docTemplatemall_admin,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfomall_admin.InstanceName(), SwaggerInfomall_admin)
}
