basePath: /
definitions:
  gin_common.GinCommonResponse:
    properties:
      data:
        description: "返回的数据是任意类型\t如果有错误，则把错误信息也封装在此\n\n\t\t{\n\t\t\t\"err_code\":
          300000,\n\t\t\t\"err_msg\": \"用户名已存在\"\n\t\t}"
      status:
        description: success or fail
        type: string
    type: object
  ums_admin.UmsAdminLogin:
    properties:
      password:
        description: 密文密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  ums_admin.UmsAdminPage:
    properties:
      page_num:
        default: 1
        description: 页码
        type: integer
      page_size:
        default: 10
        description: 每页数量
        type: integer
      username:
        description: 用户名
        type: string
    required:
    - page_num
    - page_size
    type: object
  ums_admin.UmsAdminRegisterRequest:
    properties:
      email:
        description: 邮箱
        type: string
      icon:
        description: 用户头像
        type: string
      nickname:
        description: 用户昵称
        type: string
      note:
        description: 备注
        type: string
      password:
        description: 密文密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  ums_admin.UmsAdminUpdate:
    properties:
      email:
        description: 邮箱
        type: string
      icon:
        description: 用户头像
        type: string
      nickname:
        description: 用户昵称
        type: string
      note:
        description: 备注
        type: string
      password:
        description: 密文密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: mall-go API
  title: mall-go API
  version: v1
paths:
  /admin/{user_id}:
    get:
      consumes:
      - application/json
      description: 根据用户 ID 获取用户信息
      parameters:
      - description: 用户 ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      security:
      - GinJWTMiddleware: []
      summary: 根据用户 ID 获取用户信息
      tags:
      - 后台用户管理
  /admin/authTest:
    get:
      consumes:
      - application/json
      description: 用户鉴权测试
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      summary: 用户鉴权测试
      tags:
      - 后台用户管理
  /admin/info:
    get:
      consumes:
      - application/json
      description: 根据用户 ID 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      security:
      - GinJWTMiddleware: []
      summary: 根据用户 ID 获取用户信息
      tags:
      - 后台用户管理
  /admin/list:
    post:
      consumes:
      - application/json
      description: 分页查询用户
      parameters:
      - description: 分页查询用户
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ums_admin.UmsAdminPage'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      security:
      - GinJWTMiddleware: []
      summary: 分页查询用户
      tags:
      - 后台用户管理
  /admin/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户登录
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ums_admin.UmsAdminLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      summary: 用户登录
      tags:
      - 后台用户管理
  /admin/refreshToken:
    post:
      consumes:
      - application/json
      description: 刷新 token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      security:
      - GinJWTMiddleware: []
      summary: 刷新 token
      tags:
      - 后台用户管理
  /admin/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户注册
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ums_admin.UmsAdminRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      summary: 用户注册
      tags:
      - 后台用户管理
  /admin/update/{user_id}:
    post:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: 用户 ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: 更新用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ums_admin.UmsAdminUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_common.GinCommonResponse'
      security:
      - GinJWTMiddleware: []
      summary: 更新用户信息
      tags:
      - 后台用户管理
schemes:
- http
- https
securityDefinitions:
  GinJWTMiddleware:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
